package com.aditi.product_service.domain.model;

import com.aditi.product_service.domain.exception.InvalidProductException;

import java.util.Objects;

/**
 * The Product aggregate.
 *
 * <p>A plain Java object with <b>no JPA annotations</b> — the persistence shape
 * lives in {@code infrastructure.entity.ProductEntity}. It also enforces its own
 * invariants through the factory methods, so an invalid product cannot be
 * constructed from anywhere, including a test or a future GraphQL mutation.
 *
 * <h2>Why invariants belong here</h2>
 * "Price must be positive" is a business rule. If it is enforced only by a
 * {@code @Positive} annotation on a DTO, then any other entry point — a Feign
 * consumer, a batch import, a unit test — can still create a product with a
 * negative price. Putting the check in the constructor makes it true
 * everywhere. The DTO annotations then become a courtesy that produces a nicer
 * error message, not the only line of defence.
 */
public class Product {

    private static final int MAX_NAME_LENGTH = 200;
    private static final int MAX_CATEGORY_LENGTH = 100;
    private static final int MAX_DESCRIPTION_LENGTH = 4000;

    private final Long id;
    private final String name;
    private final Double price;
    private final String imageUrl;
    private final String category;
    private final String description;

    private Product(Long id, String name, Double price, String imageUrl,
                    String category, String description) {
        this.id = id;
        this.name = requireName(name);
        this.price = requirePrice(price);
        this.imageUrl = normalise(imageUrl);
        this.category = truncate(normalise(category), MAX_CATEGORY_LENGTH);
        this.description = truncate(normalise(description), MAX_DESCRIPTION_LENGTH);
    }

    /** Creates a new, not-yet-persisted product. */
    public static Product create(String name, Double price, String imageUrl,
                                 String category, String description) {
        return new Product(null, name, price, imageUrl, category, description);
    }

    /**
     * Returns a copy with the given fields, keeping the same id.
     *
     * <p>Immutable update: no setters means a product cannot be half-mutated,
     * and every field still passes validation. JPA then needs the entity to be
     * mutable, which is exactly why the entity is a separate class.
     */
    public Product withDetails(String name, Double price, String imageUrl,
                               String category, String description) {
        return new Product(this.id, name, price, imageUrl, category, description);
    }

    /** Returns a copy pointing at a newly uploaded image. */
    public Product withImageUrl(String newImageUrl) {
        return new Product(this.id, this.name, this.price, newImageUrl, this.category, this.description);
    }

    /**
     * Returns a copy carrying a storage-assigned identity.
     *
     * <p>Only a persistence adapter should call this: the id is generated by the
     * database, so a use case has no business setting it. It is public because
     * the adapter lives in a different package, and the javadoc is the guard —
     * which is a fair trade for keeping the aggregate immutable.
     */
    public Product withId(Long newId) {
        return new Product(newId, this.name, this.price, this.imageUrl, this.category, this.description);
    }

    private static String requireName(String name) {
        String value = normalise(name);
        if (value == null || value.isEmpty()) {
            throw new InvalidProductException("Product name is required");
        }
        return truncate(value, MAX_NAME_LENGTH);
    }

    private static Double requirePrice(Double price) {
        if (price == null) {
            throw new InvalidProductException("Product price is required");
        }
        if (price < 0) {
            throw new InvalidProductException("Product price cannot be negative: " + price);
        }
        if (price.isNaN() || price.isInfinite()) {
            throw new InvalidProductException("Product price must be a finite number");
        }
        // Round to cents rather than letting binary floating point keep values
        // like 19.999999999999996 in a column people expect to be money.
        return Math.round(price * 100.0) / 100.0;
    }

    private static String normalise(String value) {
        return value == null ? null : value.trim();
    }

    private static String truncate(String value, int max) {
        if (value == null) {
            return null;
        }
        return value.length() <= max ? value : value.substring(0, max);
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Double getPrice() {
        return price;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public String getCategory() {
        return category;
    }

    public String getDescription() {
        return description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Product other)) {
            return false;
        }
        return Objects.equals(id, other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "Product{id=" + id + ", name='" + name + "', price=" + price + '}';
    }
}
